fix: refactor events stanza and adding allow-deny filter
janikgar/boundary-chart pull request #16
Opened 2024-03-11 19:02 UTC by msalman899

2024-03-12 07:04 UTC, janikgar requested changes
Good change; I like making the sinks configurable with the `stderr` default.

If you can adjust the misspelling on `evenevent` where it shows up, it should be good so it will be compliant HCL. Thanks!

2024-03-12 07:04 UTC, janikgar commented on charts/boundary-chart/templates/configmap.yaml
> +        evenevent_source_url = {{ $sink.evenevent_source_url }}
This should be `event_source_url` throughout

2024-03-12 07:04 UTC, janikgar commented on charts/boundary-chart/templates/configmap.yaml
> +        {{- if (and (hasKey $sink "evenevent_source_url")) }}
`event_source_url`

2024-03-12 12:29 UTC, msalman899 commented on charts/boundary-chart/templates/configmap.yaml
> +        evenevent_source_url = {{ $sink.evenevent_source_url }}
My bad, Fixed it. Thanks for checking.

2024-03-12 12:29 UTC, msalman899 commented on charts/boundary-chart/templates/configmap.yaml
> +        {{- if (and (hasKey $sink "evenevent_source_url")) }}
Fixed.

2024-03-13 02:42 UTC, janikgar approved these changes

2024-03-13 02:43 UTC, merged